In [1]:
import tensorflow as tf

2023-07-18 14:46:07.980512: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-18 14:46:17.982703: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-18 14:47:01.006385: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
DIR_PATH = '../data/processed/CK7/CK7_cvae/test'
AUTOTUNE = tf.data.AUTOTUNE
NUM_OBSERVATIONS = 17364

In [3]:
def change_inputs(image, label):
    return image, image

def normalize(image, mirrored_image):
    return (tf.cast(image, tf.float32) / 255.0, tf.cast(mirrored_image, tf.float32) / 255.0)

In [4]:
dataset = tf.keras.utils.image_dataset_from_directory(DIR_PATH, batch_size=128, image_size=(224, 224), shuffle=True)

Found 17364 files belonging to 1 classes.


2023-07-18 14:55:53.854374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13509 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:5e:00.0, compute capability: 7.5
2023-07-18 14:55:53.856894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13509 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:5f:00.0, compute capability: 7.5


In [5]:
dataset = dataset.map(change_inputs, num_parallel_calls=AUTOTUNE)

In [6]:
for img_batch, img_batch_mirror in dataset.take(1):
    for img in img_batch:
        print(img)
        break
    for img in img_batch_mirror:
        print(img)
        break

2023-07-18 15:06:13.395735: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [17364]
	 [[{{node Placeholder/_0}}]]
2023-07-18 15:06:13.399920: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [17364]
	 [[{{node Placeholder/_0}}]]
2023-07-18 15:06:23.472721: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:392] Filling up shuffle buffer (this may take a while): 192 of 1024
2023-07-18 15:06:33.446872: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:392] Filling up shuffle buffer (this may take a while): 344 of 1024
2023-07-18 1

tf.Tensor(
[[[214. 208. 222.]
  [210. 204. 216.]
  [212. 206. 218.]
  ...
  [218. 208. 198.]
  [206. 196. 186.]
  [220. 210. 198.]]

 [[217. 211. 225.]
  [211. 205. 217.]
  [208. 202. 212.]
  ...
  [227. 217. 207.]
  [216. 206. 194.]
  [209. 199. 187.]]

 [[214. 208. 220.]
  [213. 207. 219.]
  [215. 209. 219.]
  ...
  [227. 215. 203.]
  [205. 193. 181.]
  [241. 229. 215.]]

 ...

 [[185. 172. 166.]
  [231. 217. 216.]
  [237. 222. 227.]
  ...
  [234. 229. 223.]
  [230. 220. 219.]
  [234. 222. 224.]]

 [[175. 164. 158.]
  [200. 190. 188.]
  [197. 186. 192.]
  ...
  [237. 233. 224.]
  [240. 232. 229.]
  [196. 186. 185.]]

 [[182. 173. 166.]
  [171. 161. 159.]
  [181. 172. 177.]
  ...
  [239. 235. 224.]
  [241. 234. 228.]
  [203. 193. 191.]]], shape=(224, 224, 3), dtype=float32)
tf.Tensor(
[[[214. 208. 222.]
  [210. 204. 216.]
  [212. 206. 218.]
  ...
  [218. 208. 198.]
  [206. 196. 186.]
  [220. 210. 198.]]

 [[217. 211. 225.]
  [211. 205. 217.]
  [208. 202. 212.]
  ...
  [227. 217. 207.]

In [7]:
dataset = dataset.map(normalize, num_parallel_calls=AUTOTUNE)
for img_batch, img_batch_mirror in dataset.take(1):
    for img in img_batch:
        print(img)
        break
    for img in img_batch_mirror:
        print(img)
        break

2023-07-18 12:57:24.709805: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [17364]
	 [[{{node Placeholder/_0}}]]
2023-07-18 12:57:24.711178: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [17364]
	 [[{{node Placeholder/_0}}]]


tf.Tensor(
[[[0.7137255  0.60784316 0.5254902 ]
  [0.36862746 0.2627451  0.18039216]
  [0.48235294 0.37254903 0.2901961 ]
  ...
  [0.6627451  0.5803922  0.49803922]
  [0.7372549  0.65882355 0.5647059 ]
  [0.84705883 0.76862746 0.6745098 ]]

 [[0.5568628  0.4509804  0.3764706 ]
  [0.34117648 0.23529412 0.16078432]
  [0.24705882 0.14117648 0.06666667]
  ...
  [0.7529412  0.67058825 0.5882353 ]
  [0.8392157  0.75686276 0.6745098 ]
  [0.8784314  0.8        0.7058824 ]]

 [[0.6039216  0.5019608  0.44313726]
  [0.54901963 0.44705883 0.3882353 ]
  [0.60784316 0.5058824  0.44705883]
  ...
  [0.7372549  0.654902   0.5803922 ]
  [0.7176471  0.627451   0.5568628 ]
  [0.8039216  0.7176471  0.63529414]]

 ...

 [[0.94509804 0.85882354 0.80784315]
  [0.9764706  0.9137255  0.8627451 ]
  [0.92156863 0.8862745  0.85882354]
  ...
  [0.6117647  0.5019608  0.41960785]
  [0.68235296 0.5686275  0.49803922]
  [0.6745098  0.56078434 0.49019608]]

 [[0.6313726  0.5411765  0.4862745 ]
  [0.6666667  0.59607846 0

In [8]:
dataset = dataset.cache()

for img_batch, img_batch_mirror in dataset:
    print(img_batch.shape)
    print(img_batch_mirror.shape)
    break

2023-07-18 12:57:32.230866: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int32 and shape [17364]
	 [[{{node Placeholder/_4}}]]
2023-07-18 12:57:32.232049: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [17364]
	 [[{{node Placeholder/_0}}]]


(128, 224, 224, 3)
(128, 224, 224, 3)


2023-07-18 12:57:33.528639: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [ ]:
dataset = dataset.prefetch(AUTOTUNE)
dataset

2023-07-18 14:42:48.269843: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int32 and shape [17364]
	 [[{{node Placeholder/_4}}]]
2023-07-18 14:42:48.273849: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [17364]
	 [[{{node Placeholder/_0}}]]
2023-07-18 14:42:59.106230: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:392] Filling up shuffle buffer (this may take a while): 144 of 1024
2023-07-18 14:43:10.307347: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:392] Filling up shuffle buffer (this may take a while): 263 of 1024
2023-07-18 14